### ISSUE TITLE
Empty array returned

### ISSUE THREAD

**Issue by jaspal747** [agentile/PHP-Stanford-NLP#1]
Hi,

I am trying to use this POSTager as described in the steps. However, I am getting an empty array as output. I have tried using your php parser on both cmd line and via browser. I am getting an empty array as output on both.

I am using the latest version (3.3.1) of the stanford post tagger (stanford-postagger-2014-01-04) of 35 MB size. I have tested this via their GUI and it works fine.

Any help would be highy apreciated.

Thanks

**Comment by domarco** [comment]
@samkool did change the variable declaration on line 122/123/124 fix the issue, because I still got an error, Are you mean 122/123/124 line code is inside $descriptorspec = array(  ?

**Comment by ami007** [comment]
india is our country.

**Comment by diegorodriguezvidal** [comment]
@domarco @samkool  I've got the same issue. Did you solve that problem?

**Comment by domarco** [comment]
@diegorodriguezvidal try using version stanford-postagger-2015-04-20, it solve my problem. And don't forget to manually defined your postagger library path. Example like below:
`$pos = new \StanfordNLP\POSTagger(`
    `'D:/Project/NLP/stanford-postagger-2015-04-20/models/english-left3words-distsim.tagger',` 
    `'D:/Project/NLP/stanford-postagger-2015-04-20/stanford-postagger.jar'`
`);`
String "D:/Project/NLP" was my folder path to "stanford-postagger-2015-04-20" folder.
You can save the path to a "$variable" first, write it as 
Have fun, hope this help.
*I'm using windows and the codes works fine.

**Comment by diegorodriguezvidal** [comment]
@domarco Thanks for the help, I tried your approach and it doesn't work for me. In my case everything is working on localhost. I am just having this error code in production: Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedParser and I don't know how to solve it...

**Comment by samkool** [comment]
Hey Diego,
Ill look at whrn I get home monday!

**Comment by samarthbhasin** [comment]
> @domarco Thanks for the help, I tried your approach and it doesn't work for me. In my case everything is working on localhost. I am just having this error code in production: Error: Could not find or load main class edu.stanford.nlp.parser.lexparser.LexicalizedParser and I don't know how to solve it...

Hi @diegorodriguezvidal , did you ever solve this? I'm having a similar issue. I'm trying to load the Stanford-ner.jar on Spark executors on AWS EMR cluster. My code just can't find or load the main class.

**Comment by domarco** [comment]
@samarthbhasin have you tried my approach to manually define your filepath? 
try using version: stanford-postagger-2015-04-20 <- this was the stable version.
Your error mean that it cannot find the file, mainly because of a wrong path.

**Comment by samarthbhasin** [comment]
@domarco this is what the error looks like, which includes the java command being executed. from this it seems like it can definitely find the jar file, only problem is it is unable to load the main class... not sure why

OSError: Java command failed : ['/usr/lib/jvm/java-1.8.0/bin/java', '-mx4096m', '-cp', '/home/hadoop/stanford/stanford-ner-production/stanford-ner-3.9.1-sources.jar:/home/hadoop/stanford/stanford-ner-production/slf4j-log4j12-1.7.25.jar:/home/hadoop/stanford/stanford-ner-production/stanford-ner-3.9.1.jar:/home/hadoop/stanford/stanford-ner-production/stanford-ner-3.9.1-javadoc.jar:/home/hadoop/stanford/stanford-ner-production/stanford-ner.jar:/home/hadoop/stanford/stanford-ner-production/slf4j-api-1.7.25.jar:/home/hadoop/stanford/stanford-ner-production/lib/joda-time.jar:/home/hadoop/stanford/stanford-ner-production/lib/jollyday-0.4.9.jar:/home/hadoop/stanford/stanford-ner-production/lib/stanford-ner-resources.jar', 'edu.stanford.nlp.ie.crf.CRFClassifier', '-loadClassifier', '/home/hadoop/stanford/stanford-ner-production/classifiers/english.all.3class.distsim.crf.ser.gz', '-textFile', '/tmp/tmpdJuvgP', '-outputFormat', 'slashTags', '-tokenizerFactory', 'edu.stanford.nlp.process.WhitespaceTokenizer', '-tokenizerOptions', '"tokenizeNLs=false"', '-encoding', 'utf-8']
