### ISSUE TITLE
Issue with NERTagger. Processes only the first sentence.

### ISSUE THREAD

**Issue by NameIvan** [agentile/PHP-Stanford-NLP#15]
I think here is bug.
From your exapmle

```
$pos = new \StanfordNLP\NERTagger(
  '/path/to/stanford-ner-2013-11-12/classifiers/english.all.3class.distsim.crf.ser.gz',
  '/path/to/stanford-ner-2013-11-12/stanford-ner.jar'
);

$result = $pos->tag(explode(' ', "The Federal Reserve Bank of New York led by Timothy R. Geithner."));
var_dump($result);
```

If sentence  is "The Federal Reserve Bank of New York led by Timothy R. Geithner. He also said that we should call the Internal Revenue Services office" (Nlp.stanford detect "Internal Revenue Services"  as ORGANIZATION), it will return result only for first sentence.

The proposed solution

file StanfordTagger.php  method tag()  string 91
now 
`return isset($results[0]) ? $results[0] : array();`

updated
`return isset($results[0]) ? $results : array();`

**Comment by rraub** [comment]
Furthermore the reference implementation returns tagged sentences.  http://www.nltk.org/_modules/nltk/tag/stanford.html#StanfordTagger

**Comment by agentile** [comment]
@NameIvan @rraub Thank you, this has been updated.
