### ISSUE TITLE
proc_open(): CreateProcess failed  . . . ..\StanfordNlp\StanfordTagger.php on line 159

### ISSUE THREAD

**Issue by domarco** [agentile/PHP-Stanford-NLP#18]
```
<?php
include('PHP-Stanford-NLP-master/autoload.php');

require_once 'PHP-Stanford-NLP-master/src/StanfordNLP/Base.php';
require_once 'PHP-Stanford-NLP-master/src/StanfordNLP/StanfordTagger.php';
require_once 'PHP-Stanford-NLP-master/src/StanfordNLP/POSTagger.php';

$path = "C:/xampp/...../stanford-postagger-full-2015-12-09";

$pos = new \StanfordNlp\POSTagger(
  $path.'/models/english-left3words-distsim.tagger',
  $path.'/stanford-postagger.jar'
);

$result = $pos->tag(explode(' ', "What does the fox say?"));
var_dump($result);

```
The Output is an empty array:
array(0) { } 

i try to run $cmd in command prompt (the java global code is working in my windows 7) but it says:
error: Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory 
.....
.....

**Comment by domarco** [comment]
Try to set the java path manually before $pos->tag don't work; did the javapath format is correct?

$pos->setJavaPath('C:\Program Files\Java\jre1.8.0_45\bin\java.exe');

**Comment by domarco** [comment]
Ah sorry found the error by using version 3.5.2 like mention in #7 . 
Explain by alvation in nltk issue #1237 that NLTK not yet catches up with Standford tools.
Thanks

**Comment by Mnosek** [comment]
Are you sure that you use absolute path in $path variable here?

`$pos = new StanfordNLP\POSTagger(
     $path.'/models/english-left3words-distsim.tagger',
     $path.'/stanford-postagger.jar:'.$path.'/lib/slf4j-api.jar'
);`

**Comment by domarco** [comment]
Yeah,
