### ISSUE TITLE
Penn Only

### ISSUE THREAD

**Issue by AdamNix** [agentile/PHP-Stanford-NLP#23]
Hi

Is there a way to output only the Penn results?
   
        // Word and tags is first
        // penn is second
        // typed dependencies is last.

Wonderful program.

**Comment by agentile** [comment]
Hi Adam,

Are you meaning just 

```php
$result = $parser->parseSentence("What does the fox say?");
var_dump($result['penn']);
```

Or are you wanting for `$parser->parseSentence("What does the fox say?");` to just do the penn work doing something like `$parser->parseSentence("What does the fox say?", ['penn']);` ?

FWIW , I do plan to revisit this project and address a lot of the issues people have been having and make it more up to date.

**Comment by AdamNix** [comment]
Thanks for the reply, Anthony.
I believe at lot of the issues revolve trying to sync three areas, Java updates/PHP/Stanford Parser updates.
e.g When I run either of the suggestions above I get:

array(2) {
  ["parent"]=>
  NULL
  ["children"]=>
  array(0) {
  }
}

I am using PHP 7.1, Stanford and:
'C:\stanford-parser-full-2015-04-20\stanford-parser.jar',
'C:\stanford-parser-full-2015-04-20\stanford-parser-3.5.2-models.jar'

Using the original example, I flattened the array and would be able to get rid of the 'words and tags' using a search for '(ROOT'
The Universal dependencies(typed dependencies) are a little more difficult.

**Comment by agentile** [comment]
@AdamNix Hmm, yeah, I am not sure why you are getting an array like that.

I just updated the repo, retesting against stanford version 3.8.0 ... here is what I am running Java and PHP wise

```
agentile@agentile:~/php-stanford$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)


agentile@agentile:~/php-stanford$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

Here is what I ran https://github.com/agentile/PHP-Stanford-NLP/blob/master/examples/stanford.php

Notice the commented out bits, if you setDebug, it will echo out the actual command sent behind the scenes, e.g.

```sh
agentile@agentile:~/php-stanford/examples$ php stanford.php 
DEBUG: Command used: java -mx300m -cp "/home/agentile/php-stanford/stanford-parser-full-2017-06-09/stanford-parser.jar:/home/agentile/php-stanford/stanford-parser-full-2017-06-09/stanford-parser-3.8.0-models.jar" edu.stanford.nlp.parser.lexparser.LexicalizedParser -encoding UTF-8 -outputFormat "wordsAndTags,penn,typedDependencies" edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz /tmp/phpnlpparserYRVcyk
```

If you set `$parser->setOutputFormat('penn');`

Then it will only do that format, and the values for `wordsAngTags` and `typedDependencies` will be `null`

You should be getting back an associative array. 

So if you can possibly do a few things:

Tell me if you are running on unix or windows and if you can copy paste more of the code that you are running, as it is hard for me to debug clearly on your behalf without more information. Can you also update to stanford version 3.8.0?

**Comment by agentile** [comment]
```
agentile@agentile:~/php-stanford/examples$ java -mx300m -cp "/home/agentile/php-stanford/stanford-parser-full-2017-06-09/stanford-parser.jar:/home/agentile/php-stanford/stanford-parser-full-2017-06-09/stanford-parser-3.8.0-models.jar" edu.stanford.nlp.parser.lexparser.LexicalizedParser -encoding UTF-8 -outputFormat "wordsAndTags,penn,typedDependencies" edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz /tmp/test
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.7 sec].
Parsing file: /tmp/test
Parsing [sent. 1 len. 6]: What does the fox say ?
What/WP does/VBZ the/DT fox/NN say/VB ?/.

(ROOT
  (SBARQ
    (WHNP (WP What))
    (SQ (VBZ does)
      (NP (DT the) (NN fox))
      (VP (VB say)))
    (. ?)))

dobj(say-5, What-1)
aux(say-5, does-2)
det(fox-4, the-3)
nsubj(say-5, fox-4)
root(ROOT-0, say-5)

Parsed file: /tmp/test [1 sentences].
Parsed 6 words in 1 sentences (9.63 wds/sec; 1.61 sents/sec).
```

**Comment by AdamNix** [comment]
I'm using Windows 7 Pro
I've updated to stanford version 3.8.0.
I have the Stanford Parser and Postagger both zipped and unzipped in a file called Stanford.
My PHP file is there too. 
When I run the below program for $results[penn] I get an empty array,

`
/**
 * This file is part of the StanfordNLP for PHP.
 *
 * Base class, providing core functionality for several classes.
 *
 * @package StanfordNLP
 * @link https://github.com/agentile/PHP-Stanford-NLP
 * @version 0.1.0
 * @author Anthony Gentile <asgentile@gmail.com>
 */
namespace StanfordNLP;
/**
*
* Base Exception class for Stanford NLP
*
* @package StanfordNLP
*
*/
class Base {
    /**
     * Java path
     *
     * relative/absolute path to java
     * e.g. /usr/bin/java
     */
    protected $java_path = 'java'; // assume relative path to start
    /**
     * Stanford Jar file
     */
    protected $jar;
    /**
     * Stanford Models Jar file
     */
    protected $models_jar;
    /**
     * Java options to use with our jar instance
     */
    protected $java_options;
    /**
     * Output from NLP Tool
     */
    protected $output = null;
    /**
     * Errors from NLP Tool
     */
    protected $errors = null;
    /**
     * PHP Operating System
     */
    protected $php_os = 'linux';
    /**
     * Constructor!
     *   - Set PHP Operating System.
     *
     * @return null
     */
    public function __construct()
    {
        if (defined('PHP_OS')) {
            if (strtolower(substr(PHP_OS, 0, 3)) == 'win') {
                $this->php_os = 'windows';
            }
        }
    }
    /**
     * Java path setter
     *
     * @param $java_path string path to java executable
     *
     * @return null
     */
    public function setJavaPath($java_path)
    {
        $this->java_path = $java_path;
    }
    /**
     * Java path getter
     *
     * @return string
     */
    public function getJavaPath()
    {
        return $this->java_path;
    }
    /**
     * Jar setter
     *
     * @param $jar string path to jar file
     *
     * @return null
     */
    public function setJar($jar)
    {
        if (file_exists($jar)) {
            $this->jar = $jar;
        } else {
            throw new Exception("Jar file path does not exist.");
        }
    }
    /**
     * Jar getter
     *
     * @return mixed
     */
    public function getJar()
    {
        return $this->jar;
    }
    /**
     * Models Jar setter
     *
     * @param $jar string path to jar file
     *
     * @return null
     */
    public function setModelsJar($jar)
    {
        if (file_exists($jar)) {
            $this->models_jar = $jar;
        } else {
            throw new Exception("Models Jar file path does not exist.");
        }
    }
    /**
     * Models Jar getter
     *
     * @return mixed
     */
    public function getModelsJar()
    {
        return $this->models_jar;
    }
    /**
     * Java options setter
     *
     * @param $options mixed java options
     *
     * @return null
     */
    public function setJavaOptions($options)
    {
        $this->java_options = (array) $options;
    }
    /**
     * Java options getter
     *
     * @return array
     */
    public function getJavaOptions()
    {
        return $this->java_options;
    }
    /**
     * Output setter
     *
     * @param $output
     *
     * @return null
     */
    public function setOutput($output)
    {
        $this->output = $output;
    }
    /**
     * Output getter
     *
     * @return mixed
     */
    public function getOutput()
    {
        return $this->output;
    }
    /**
     * Errors setter
     *
     * @param $errors
     *
     * @return null
     */
    public function setErrors($errors)
    {
        $this->errors = $errors;
    }
    /**
     * Errors getter
     *
     * @return mixed
     */
    public function getErrors()
    {
        return $this->errors;
    }
}

/**
 * This file is part of the StanfordNLP for PHP.
 * 
 * Exception class
 * 
 * @package StanfordNLP
 * @link https://github.com/agentile/PHP-Stanford-NLP
 * @version 0.1.0
 * @author Anthony Gentile <asgentile@gmail.com>
 */
namespace StanfordNLP;
/**
*
* Base Exception class for Stanford NLP
*
* @package StanfordNLP
*
*/
class Exception extends \Exception
{
}

/**
 * PHP interface for Stanford Taggers (NER, POS Tagger)
 * e.g. http://nlp.stanford.edu/downloads/tagger.shtml
 *
 * Mimicks http://nltk.org/_modules/nltk/tag/stanford.html#StanfordTagger
 *
 *
 * @link https://github.com/agentile/PHP-Stanford-NLP
 * @version 0.1.0
 * @author Anthony Gentile <asgentile@gmail.com>
 */
namespace StanfordNLP;
class StanfordTagger extends Base {
    /**
     * Tag separator
     */
    protected $separator = '_';
    /**
     * Tag type
     */
    protected $tag_type = 'pos';
    /**
     * Constructor!
     *
     * @return null
     */
    public function __construct()
    {
        parent::__construct();
    }
    /**
     * Separator setter
     *
     * @param $output
     *
     * @return null
     */
    public function setSeparator($separator)
    {
        $this->separator = $separator;
    }
    /**
     * Separator getter
     *
     * @return mixed
     */
    public function getSeparator()
    {
        return $this->separator;
    }
    /**
     * Tag type setter
     *
     * @param $type
     *
     * @return null
     */
    public function setTagType($type)
    {
        $this->tag_type = $type;
    }
    /**
     * Tag type getter
     *
     * @return mixed
     */
    public function getTagType()
    {
        return $this->tag_type;
    }
    /**
     * Tag from an array of tokens for a sentence
     *
     * @param $tokens array tokens
     *
     * @return mixed
     */
    public function tag($tokens)
    {
        $results = $this->batchTag(array($tokens));
        return isset($results[0]) ? $results[0] : array();
    }
    /**
     * Tag multiple arrays of tokens for sentences
     *
     * @param $sentences array array of arrays of tokens
     *
     * @return mixed
     */
    public function batchTag($sentences)
    {
        // Reset errors and output
        $this->setErrors(null);
        $this->setOutput(null);
        // Make temp file to store sentences.
        $tmpfname = tempnam(DIRECTORY_SEPARATOR . 'tmp', 'phpnlptag');
        chmod($tmpfname, 0644);
        $handle = fopen($tmpfname, "w");
        foreach ($sentences as $k => $v) {
            $sentences[$k] = implode(' ', $v);
        }
        $str = implode("\n", $sentences);
        fwrite($handle, $str);
        fclose($handle);
        // Create process to run stanford ner.
        $descriptorspec = array(
           0 => array("pipe", "r"),  // stdin
           1 => array("pipe", "w"),  // stdout
           2 => array("pipe", "w")   // stderr
        );
        $options = implode(' ', $this->getJavaOptions());
        $osSeparator = $this->php_os == 'windows' ? ';' : ':';
        switch ($this->getTagType()) {
            case 'pos':
                $separator = $this->getSeparator();
                $cmd = escapeshellcmd(
                    $this->getJavaPath()
                    . " $options -cp \""
                    . $this->getJar()
                    . "{$osSeparator}\" edu.stanford.nlp.tagger.maxent.MaxentTagger -model "
                    . $this->getModel()
                    . " -textFile "
                    . $tmpfname
                    . " -outputFormat slashTags -tagSeparator "
                    . $separator
                    . " -encoding utf8"
                );
            break;
            case 'ner':
                $cmd = escapeshellcmd(
                    $this->getJavaPath()
                    . " $options -cp \""
                    . $this->getJar()
                    . "{$osSeparator}\" edu.stanford.nlp.ie.crf.CRFClassifier -loadClassifier "
                    . $this->getClassifier()
                    . " -textFile "
                    . $tmpfname
                    . " -encoding utf8"
                );
            break;
        }
        $process = proc_open($cmd, $descriptorspec, $pipes, dirname($this->getJar()));
        $output = null;
        $errors = null;
        if (is_resource($process)) {
            // We aren't working with stdin
            fclose($pipes[0]);
            // Get output
            $output = stream_get_contents($pipes[1]);
            fclose($pipes[1]);
            // Get any errors
            $errors = stream_get_contents($pipes[2]);
            fclose($pipes[2]);
            // close pipe before calling proc_close in order to avoid a deadlock
            $return_value = proc_close($process);
            if ($return_value == -1) {
                throw new Exception("Java process returned with an error (proc_close).");
            }
        }
        unlink($tmpfname);
        if ($errors) {
            $this->setErrors($errors);
        }
        if ($output) {
            $this->setOutput($output);
        }
        return $this->parseOutput();
    }
    /**
     * Build text output from jar into array structure
     *
     * @return array
     */
    public function parseOutput()
    {
        $output = $this->getOutput();
        if (!$output) {
            return array();
        }
        $separator = $this->getSeparator();
        $arr = array();
        $sentences = explode("\n", $output);
        foreach ($sentences as $sentence) {
            if (trim($sentence) == '') {
                continue;
            }
            $s = array();
            $tagged = explode(' ', trim($sentence));
            foreach ($tagged as $tag) {
                $parts = explode($separator, $tag);
                $pos = array_pop($parts);
                $s[] = array(implode($separator, $parts), $pos);
            }
            $arr[] = $s;
        }
        return $arr;
    }
}

/**
 * PHP interface for Stanford Parser
 * http://nlp.stanford.edu/software/lex-parser.shtml
 *
 *
 * @link https://github.com/agentile/PHP-Stanford-NLP
 * @version 0.1.0
 * @author Anthony Gentile <asgentile@gmail.com>
 */
namespace StanfordNLP;
class Parser extends Base {
    /**
     * Output format?
     *
     * CSV style list of output types
     * e.g. penn,typedDependencies,wordsAndTags
     */
    public $output_format = "wordsAndTags,penn,typedDependencies";
    /**
     * Use lexicalized parser?
     */
    public $lexicalized_parser = false;
    /**
     * Constructor!
     *
     * @param $model string path to tagging model file
     * @param $jar string path stanford parser jar file
     * @param $java_options mixed command line arguments to pass
     *
     * @return null
     */
    public function __construct($jar, $models_jar = null, $java_options = array('-mx300m'))
    {
        parent::__construct();
        $this->setJar($jar);
        $this->setModelsJar($models_jar);
        $this->setJavaOptions($java_options);
    }
    /**
     * Parse sentence
     *
     * @param $tokens array tokens
     *
     * @return mixed
     */
    public function parseSentence($sentence)
    {
        $results = $this->parseSentences(array($sentence));
        return isset($results[0]) ? $results[0] : array();
    }
    /**
     * Parse array of sentences
     *
     * @param $sentences array of sentences
     *
     * @return mixed
     */
    public function parseSentences($sentences)
    {
        // Reset errors and output
        $this->setErrors(null);
        $this->setOutput(null);
        // Make temp file to store sentences.
        $tmpfname = tempnam(DIRECTORY_SEPARATOR . 'tmp', 'phpnlpparser');
        chmod($tmpfname, 0644);
        $handle = fopen($tmpfname, "w");
        $str = implode("\n", $sentences);
        fwrite($handle, $str);
        fclose($handle);
        // Create process to run stanford ner.
        $descriptorspec = array(
           0 => array("pipe", "r"),  // stdin
           1 => array("pipe", "w"),  // stdout
           2 => array("pipe", "w")   // stderr
        );
        $options = implode(' ', $this->getJavaOptions());
        $parser = $this->lexicalized_parser ? 'edu/stanford/nlp/models/lexparser/englishFactored.ser.gz' : 'edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz';
        $osSeparator = $this->php_os == 'windows' ? ';' : ':';
        $cmd = $this->getJavaPath()
            . " $options -cp \""
            . $this->getJar()
            . $osSeparator
            . $this->getModelsJar()
            . '" edu.stanford.nlp.parser.lexparser.LexicalizedParser -encoding UTF-8 -outputFormat "'
            . $this->getOutputFormat()
            . "\" "
            . $parser
            . " "
            . $tmpfname;
        $process = proc_open($cmd, $descriptorspec, $pipes, dirname($this->getJar()));
        $output = null;
        $errors = null;
        if (is_resource($process)) {
            // We aren't working with stdin
            fclose($pipes[0]);
            // Get output
            $output = stream_get_contents($pipes[1]);
            fclose($pipes[1]);
            // Get any errors
            $errors = stream_get_contents($pipes[2]);
            fclose($pipes[2]);
            // close pipe before calling proc_close in order to avoid a deadlock
            $return_value = proc_close($process);
            if ($return_value == -1) {
                throw new Exception("Java process returned with an error (proc_close).");
            }
        }
        unlink($tmpfname);
        if ($errors) {
            $this->setErrors($errors);
        }
        if ($output) {
            $this->setOutput($output);
        }
        return $this->parseOutput();
    }
    /**
     * Build text output from jar into array structure
     *
     * @return array
     */
    public function parseOutput()
    {
        // Output is separated by two line breaks
        // Word and tags is first
        // penn is second
        // typed dependencies is last.
        $output = explode("\n\n", trim($this->getOutput()));
        $formats = explode(',', $this->getOutputFormat());
        foreach ($formats as $k => $v) {
            $formats[$k] = trim(strtolower($v));
        }
        $count = count($formats);
        $length = count($output);
        $i = 0;
        $set = array();
        while ($i < $length) {
            $arr = array(
                'wordsAndTags' => null,
                'penn' => null,
                'typedDependencies' => null,
            );
            $index_offset = 0;
            if (in_array('wordsandtags', $formats)) {
                $arr['wordsAndTags'] = $this->parseWordsAndTags($output[$i+$index_offset]);
                $index_offset++;
            }
            if (in_array('penn', $formats)) {
                $arr['penn'] = $this->parsePenn($output[$i+$index_offset]);
                $index_offset++;
            }
            if (in_array('typeddependencies', $formats)) {
                $arr['typedDependencies'] = $this->parseTypedDependencies($output[$i+$index_offset]);
            }
            $set[] = $arr;
            $i += $count;
        }
        return $set;
    }
    /**
     * POS tags into array structure
     *
     * @return array
     */
    public function parseWordsAndTags($str)
    {
        $arr = array();
        if (trim($str) == '') {
            return $arr;
        }
        $s = array();
        $tagged = explode(' ', trim($str));
        foreach ($tagged as $tag) {
            $parts = explode('/', $tag);
            $pos = array_pop($parts);
            $arr[] = array(implode('/', $parts), $pos);
        }
        return $arr;
    }
    /**
     * Penn into array structure
     *
     * @return array
     */
    public function parsePenn($string)
    {
        $arr = array('parent' => null, 'children' => array());
        $stack = array();
        $length = strlen($string);
        $node = '';
        $bracket = 1;
        for ($i = 1; $i < $length; $i++) {
            if ($string[$i] == '(') {
                $bracket += 1;
                $match_i = $this->getMatchingParen($string, $i);
                $arr['children'][] = $this->parsePenn(substr($string, $i, ($match_i - $i) + 1));
                $i = $match_i - 1;
            } else if ($string[$i] == ')') {
                $bracket -= 1;
                $arr['parent'] = trim($node);
            } else {
                $node .= $string[$i];
            }
            if ($bracket == 0) {
                return $arr;
            }
        }
        return $arr;
    }
    /**
     * Find the position of a matching closing bracket for a string opening bracket
     */
    public function getMatchingParen($string, $start_pos)
    {
        $length = strlen($string);
        $bracket = 1;
        foreach (range($start_pos + 1, $length) as $i) {
            if ($string[$i] == '(') {
                $bracket += 1;
            } else if ($string[$i] == ')') {
                $bracket -= 1;
            }
            if ($bracket == 0) {
                return $i;
            }
        }
    }
    /**
     * Typed dependencies into array structure
     *
     * @return array
     */
    public function parseTypedDependencies($str)
    {
        $arr = array();
        $lines = explode("\n", $str);
        foreach ($lines as $line) {
            $paren_pos = strpos($line, '(');
            if ($paren_pos === false) {
                continue;
            }
            $type = substr($line, 0, $paren_pos);
            $parts = explode(', ', substr($line, $paren_pos + 1, -1));
            $first = substr($parts[0], 0, strrpos($parts[0], '-'));
            $first_index = (int) substr($parts[0], strrpos($parts[0], '-') + 1);
            $second = substr($parts[1], 0, strrpos($parts[1], '-'));
            $second_index = (int) substr($parts[1], strrpos($parts[1], '-') + 1);
            $arr[] = array(
                'type' => $type,
                array(
                    'feature' => $first,
                    'index' => $first_index
                ),
                array(
                    'feature' => $second,
                    'index' => $second_index
                )
            );
        }
        return $arr;
    }
    /**
     * Lexicalized parser setter
     *
     * @param $bool
     *
     * @return null
     */
    public function setLexicalizedParser($bool)
    {
        $this->lexicalized_parser = (bool) $bool;
    }
    /**
     * Lexicalized parser getter
     *
     * @return boolean
     */
    public function getLexicalizedParser()
    {
        return $this->lexicalized_parser;
    }
    /**
     * Output format setter
     *
     * @param $format string
     *
     * @return null
     */
    public function setOutputFormat($format)
    {
        $this->output_format = $format;
    }
    /**
     * Output format getter
     *
     * @return mixed
     */
    public function getOutputFormat()
    {
        return $this->output_format;
    }
}

/**
 * PHP interface for Stanford NER
 * http://nlp.stanford.edu/software/CRF-NER.shtml
 *
 *
 * @link https://github.com/agentile/PHP-Stanford-NLP
 * @version 0.1.0
 * @author Anthony Gentile <asgentile@gmail.com>
 */
namespace StanfordNLP;
class NERTagger extends StanfordTagger {
    /**
     * NER classifier file
     */
    protected $classifier;
    /**
     * Constructor!
     *
     * @param $classifier string path to classifier file
     * @param $jar string path stanford ner jar file
     * @param $java_options mixed command line arguments to pass
     *
     * @return null
     */
    public function __construct($classifier, $jar, $java_options = array('-mx300m'))
    {
        parent::__construct();
        $this->setClassifier($classifier);
        $this->setJar($jar);
        $this->setJavaOptions($java_options);
    }
    /**
     * Tag multiple arrays of tokens for sentences
     *
     * @param $sentences array array of arrays of tokens
     *
     * @return mixed
     */
    public function batchTag($sentences)
    {
        $this->setSeparator('/');
        $this->setTagType('ner');
        return parent::batchTag($sentences);
    }
    /**
     * Classifier setter
     *
     * @param $classifier string path to classifier file
     *
     * @return mixed
     */
    public function setClassifier($classifier)
    {
        if (file_exists($classifier)) {
            $this->classifier = $classifier;
        } else {
            throw new Exception("Classifier file path does not exist.");
        }
    }
    /**
     * Classifier getter
     *
     * @return mixed
     */
    public function getClassifier()
    {
        return $this->classifier;
    }
}

/**
 * PHP interface for Stanford POS Tagger
 * http://nlp.stanford.edu/downloads/tagger.shtml
 *
 * Part-Of-Speech Tag List
 * http://www.ling.upenn.edu/courses/Fall_2003/ling001/penn_treebank_pos.html
 *
 * @link https://github.com/agentile/PHP-Stanford-NLP
 * @version 0.1.0
 * @author Anthony Gentile <asgentile@gmail.com>
 */
namespace StanfordNLP;
class POSTagger extends StanfordTagger {
    /**
     * Tagger model file
     */
    protected $model;
    /**
     * Constructor!
     *
     * @param $model string path to tagging model file
     * @param $jar string path stanford pos tagger jar file
     * @param $java_options mixed command line arguments to pass
     *
     * @return null
     */
    public function __construct($model, $jar, $java_options = array('-mx300m'))
    {
        parent::__construct();
        $this->setModel($model);
        $this->setJar($jar);
        $this->setJavaOptions($java_options);
    }
    /**
     * Tag multiple arrays of tokens for sentences
     *
     * @param $sentences array array of arrays of tokens
     *
     * @return mixed
     */
    public function batchTag($sentences)
    {
        $this->setTagType('pos');
        return parent::batchTag($sentences);
    }
    /**
     * Model setter
     *
     * @param $model string path to model file
     *
     * @return null
     */
    public function setModel($model)
    {
        if (file_exists($model)) {
            $this->model = $model;
        } else {
            throw new Exception("Model file path does not exist.");
        }
    }
    /**
     * Model getter
     *
     * @return mixed
     */
    public function getModel()
    {
        return $this->model;
    }
}

// autoload mimicks https://github.com/auraphp
spl_autoload_register(function ($class) {
    // the package namespace
    $ns = 'StanfordNLP';
    // what prefixes should be recognized?
    $prefixes = array(
        "{$ns}\\" => array(
            __DIR__ . '/src/' . $ns,
        ),
    );
    // go through the prefixes
    foreach ($prefixes as $prefix => $dirs) {
        // does the requested class match the namespace prefix?
        $prefix_len = strlen($prefix);
        if (substr($class, 0, $prefix_len) !== $prefix) {
            continue;
        }
        // strip the prefix off the class
        $class = substr($class, $prefix_len);
        // a partial filename
        $part = str_replace('\\', DIRECTORY_SEPARATOR, $class) . '.php';
        // go through the directories to find classes
        foreach ($dirs as $dir) {
            $dir = str_replace('/', DIRECTORY_SEPARATOR, $dir);
            $file = $dir . DIRECTORY_SEPARATOR . $part;
            if (is_readable($file)) {
                require $file;
                return;
            }
        }
    }
});

//Adam This below code comes back with no result.

// assume composer autoload
require_once dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
$path = dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR . 'stanford-parser-full-2017-06-09';
$parser = new \StanfordNLP\Parser(
  $path . DIRECTORY_SEPARATOR . 'stanford-parser.jar',
  $path . DIRECTORY_SEPARATOR . 'stanford-parser-3.8.0-models.jar'
);
//$parser->setDebug(true);
//$parser->setOutputFormat('penn');
//$result = $parser->parseSentence("What does the fox say?");
$result = $parser->parseSentences(["What does the fox say?", "Hi bob, how are you?"]);
var_dump($result);`

//Adam The below code gets me the words&tags, Penn, typed dependencies, but all in one array and it cannot be separated easily.
$parser = new \StanfordNLP\PaC:\stanford\stanford-parser-full-2018-06-09\stanford-parser.C:\stanford\stanford-parser-full-2018-06-09\stanford-parser-3.5.2-models.jar'
);

var_dump($result);

**Comment by AdamNix** [comment]
Adding $parser->setOutputFormat('penn');    seems to have done the trick.
Here is the code:


$parser = new \StanfordNLP\Parser(
  'C:\stanford\stanford-parser-full-2017-06-09\stanford-parser.jar',
  'C:\stanford\stanford-parser-full-2017-06-09\stanford-parser-3.8.0-models.jar'
);

//var_dump($result);
$parser->setOutputFormat('penn');
$result = $parser->parseSentence("What does the fox say?");
var_dump($result['penn']);


Here is the output:
StanSmitharray(2) {
  ["parent"]=>
  string(4) "ROOT"
  ["children"]=>
  array(1) {
    [0]=>
    array(2) {
      ["parent"]=>
      string(5) "SBARQ"
      ["children"]=>
      array(3) {
        [0]=>
        array(2) {
          ["parent"]=>
          string(4) "WHNP"
          ["children"]=>
          array(1) {
            [0]=>
            array(2) {
              ["parent"]=>
              string(7) "WP What"
              ["children"]=>
              array(0) {
              }
            }
          }
        }
        [1]=>
        array(2) {
          ["parent"]=>
          string(2) "SQ"
          ["children"]=>
          array(3) {
            [0]=>
            array(2) {
              ["parent"]=>
              string(8) "VBZ does"
              ["children"]=>
              array(0) {
              }
            }
            [1]=>
            array(2) {
              ["parent"]=>
              string(2) "NP"
              ["children"]=>
              array(2) {
                [0]=>
                array(2) {
                  ["parent"]=>
                  string(6) "DT the"
                  ["children"]=>
                  array(0) {
                  }
                }
                [1]=>
                array(2) {
                  ["parent"]=>
                  string(6) "NN fox"
                  ["children"]=>
                  array(0) {
                  }
                }
              }
            }
            [2]=>
            array(2) {
              ["parent"]=>
              string(2) "VP"
              ["children"]=>
              array(1) {
                [0]=>
                array(2) {
                  ["parent"]=>
                  string(6) "VB say"
                  ["children"]=>
                  array(0) {
                  }
                }
              }
            }
          }
        }
        [2]=>
        array(2) {
          ["parent"]=>
          string(3) ". ?"
          ["children"]=>
          array(0) {
          }
        }
      }
    }
  }
}
[Finished in 3.5s]

Many Thanks, Anthony,
